version: '2'

services:
  jenkins:
    image: 'jenkins/jenkins'
    container_name: jenkins
    user: root
    restart: always
    ports:
      - '8080:8080'
      - '5000:5000'
    volumes:
      - ./jenkins_home/:/var/jenkins_home
    networks: 
      - localnet

networks:
  localnet:
    name: localnet
    driver: bridge